In [1]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series
from matplotlib import pyplot as plt
%pylab inline

Populating the interactive namespace from numpy and matplotlib

In [4]:
d = pd.read_csv('tmp/0.csv', header=False)

In [5]:
d.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 99 entries, 0 to 98
Data columns (total 33 columns):
1266840_raw_html.txt    99 non-null object
64                      99 non-null int64
9                       99 non-null int64
54                      99 non-null int64
17                      99 non-null int64
37                      99 non-null int64
8                       99 non-null int64
0                       99 non-null int64
17.1                    99 non-null int64
33                      99 non-null int64
4                       99 non-null int64
47                      99 non-null int64
17.2                    99 non-null int64
3                       99 non-null int64
14                      99 non-null int64
2                       99 non-null int64
0.1                     99 non-null int64
13                      99 non-null int64
5                       99 non-null int64
1358                    99 non-null int64
174                     99 non-null int64
5.70689655172           99 non-null float64
17.3                    99 non-null int64
308                     99 non-null int64
0.2                     99 non-null int64
0.3                     99 non-null int64
0.4                     99 non-null int64
2.1                     99 non-null int64
5.1                     99 non-null int64
0.5                     99 non-null int64
0.6                     99 non-null int64
0.7                     99 non-null int64
0.8                     99 non-null int64
dtypes: float64(1), int64(31), object(1)
memory usage: 26.3+ KB

In [7]:
d.describe().T

,count,mean,std,min,25%,50%,75%,max
64,99,1780.343434,17087.886108,4,43.500000,60.00000,78.500000,170085
9,99,850.070707,8354.436700,1,7.000000,10.00000,13.500000,83136
54,99,118.919192,111.182941,0,42.500000,88.00000,160.500000,490
17,99,43.797980,82.653689,0,2.000000,9.00000,42.000000,362
37,99,75.121212,76.448765,0,13.500000,52.00000,120.500000,427
8,99,67.989899,76.684684,0,11.000000,44.00000,101.000000,427
0,99,2.505051,13.162543,0,0.000000,0.00000,1.000000,116
17.1,99,45.777778,86.557231,0,2.000000,9.00000,41.500000,409
33,99,65.808081,74.097382,0,9.000000,39.00000,95.000000,401
4,99,5.505051,9.872011,0,0.000000,2.00000,5.000000,67
47,99,109.616162,103.204444,0,37.500000,81.00000,150.000000,475
17.2,99,25.141414,31.028956,0,5.500000,14.00000,31.000000,169
3,99,5.111111,16.485546,0,0.000000,0.00000,1.000000,125
14,99,20.030303,27.022083,0,2.000000,10.00000,27.000000,169
2,99,10.050505,16.436876,0,1.000000,3.00000,12.500000,102
0.1,99,2.333333,4.921838,0,0.000000,0.00000,2.000000,32
13,99,6.494949,11.708512,0,0.500000,3.00000,7.000000,78
5,99,28.141414,55.305093,0,3.000000,14.00000,27.500000,474
1358,99,8786.747475,27223.883021,0,349.000000,2619.00000,6064.500000,207584
174,99,1349.818182,4607.906952,1,42.000000,337.00000,796.000000,35343
5.70689655172,99,3.852201,1.820232,0,4.224101,4.49725,4.790445,6
17.3,99,132.888889,222.042692,0,14.000000,67.00000,187.000000,1814
308,99,4192.030303,18156.506650,0,139.000000,865.00000,1965.000000,158848
0.2,99,0.848485,6.856196,0,0.000000,0.00000,0.000000,68
0.3,99,1.000000,7.613093,0,0.000000,0.00000,0.000000,75
0.4,99,2.323232,15.893670,0,0.000000,0.00000,0.000000,157
2.1,99,21.565657,99.724535,0,0.000000,3.00000,9.000000,805
5.1,99,54.737374,152.059574,0,2.500000,16.00000,50.500000,1199
0.5,99,4.303030,15.048530,0,0.000000,0.00000,2.000000,127
0.6,99,19.707071,150.232083,0,0.000000,0.00000,0.000000,1427
0.7,99,0.505051,2.528909,0,0.000000,0.00000,0.000000,21
0.8,99,0.000000,0.000000,0,0.000000,0.00000,0.000000,0